language: python
python:
    - "2.7"
    - "3.4"
    - "pypy"
    - "pypy3"
install: 
    - "pip install -r requirements.txt --use-mirrors"
script: 
    - "python setup.py test"
notifications:
  slack: zoetrope:482UogKFnS2tBTvDl7NX9daa