language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements.txt --use-mirrors
script:
- python setup.py test
deploy:
  provider: pypi
  user: benhowes
  password:
    secure: PMu6FTOkBJWjtFsJFT89DXc05jogzhYfiX3nL6rIp/Y65+BTUaG/m4vvvzfUGByEII5vSUDFjkNFvKqeC7WQgbVbKFkml1VOHEg2rdMu9MFG9wZ8qZSz4JXxUfoOCpSiJiDG0zf2ISihCKgB9JXpFCicQC/DeOptKYtBlmAV8GYvDrD3KW9iyHj+X2G3MBVzjYVO8GGDmaVexXM4XN7YcAXqFY2S+dE6+rIMKc+Xd4obDON/b0mlRTLSU8is4bOFcRtRc2osWTh2syvscUras330jRFYDuGZGPxHi9J4aIRh++OQ7Ev5Y03XkWgne6KpPlESollRashduVXRIEqYAYyWJFQ94aJdDsAWSEe8HUjn9Y7e+yNkKRuHAjYATm2FSj50/4xtlrZi2mW/m7/Rl5PJW1T819xvhDnXcg9LjM8pxP4dE0WtgY4RS8EHsCYgQN+8qoGvxB5XVW/hJq2s1csDXIhMdPD6NMkaw1oZQti7IP24Jr65Tq6NULfMyUpoUnX0C5rgfsdfFkEJyVaSj2x9dlTRvxZQnVdZmDD1Ei5gJ5vm0Z+MoHOeMXWCLnzChFMjMo7d7E4fwiGDCAmkQS5uBMtPsAUCWu9ZFBNNiTghdYnN/EPsQtFfLfK0w1QdOVarXblx4BFG0jr3Ux/UMWh/3bfhhp0dp/GNF9JjtuY=
  on:
    tags: true
    repo: ZoetropeLabs/keenmqtt
    branch: master
